swagger: '2.0'
info:
  version: "1.0.0"
  title: "banco digital"
  description: "modelar api de um banco"
  contact:
    name: "suporte"
    email: "tmsmanzi@gmail.com"
basePath: "/v2"
schemes: 
   - "https"

paths:
  /health:
    get:
      summary: "rota de healthcheck da aplicacao"
      operationId: "health"
      produces:
        - "application/json"
      responses:
        200:
  
#post em /contas
#get em /contas/{agencia}/{conta}
#get em /conta/{agencia}/{conta}/extrato
#post em /conta/{agencia}/{conta}/favorecidos
#put em /conta/{agencia}/{conta}/favorecidos/{id}
#delete em /contas/{agencia}/{conta}/favorecidos/{id}
#post em /conta/{agencia}/{conta}/transferencias
#get em /conta/{agencia}/{conta}/transferencias
  /contas:
    post:
      summary: 
      description: 
      responses:
        200:
          description: OK
    
      
definitions:
  
  
